               JOB  Fortran compiler -- Arith Phase Four -- phase 36
               CTL  6611
     *
     * Strings generated by Arith Phase Two are optimized to reduce
     * the number of temporary storage areas for each statement.
     *
     * On entry, X1 is the top of the topmost statement in low core
     * that is neither an assignment nor if statement, X2 is the top
     * of the topmost statement in high core that is neither an
     * assignment nor if statement, X3 is the top of the prefix of
     * the topmost statement in high coore that is either an
     * assignment or if statement, and 81-83 is the GMWM above the
     * topmost statement in high core.
     *
     x1        equ  89
     x2        equ  94
     x3        equ  99
     *
     * Stuff in the resident area
     *
     phasid    equ  110  Phase ID, for snapshot dumps
     sawneg    equ  123  Saw negation operator (unary minus) if no WM
     snapsh    equ  333  Core dump snapshot
     loadnx    equ  700  Load next overlay
     clearl    equ  707  CS at start of overlay loader
     *
     * Runtime addresses
     *
     aritf     equ  700
     *
     110       dcw  @arith 4@
     *
               ORG  838
     loaddd    equ  *&1          Load address
  838beginn    BCE  done,x2,.
  846          SW   gm
  850          SBR  sx3,0&X3
  857          SBR  x1,1&X1
  864          SBR  x2,1&X2
  871loop      S    wrktop
  875          C    x2,sx3
  882          BE   done
  887          MCW  kb4,3021
  894          SBR  sx1,0&X1
  901outer     MCW  kb4,op2
  908          CW   flag
  912          B    setup
  916          BCE  testeq,w18a-2,<
  924middle    BCE  1166,w18b-2,<
  932          BCE  1733,1&X2,}
  940          BW   1302,flag
  948inner     A    k3999,2972
  955          MCW  2972,x3
  962          BCE  inner,work&X3,1
  970          B    outer
  974testeq    BCE  middle,op,#
  982          BCE  1328,op,.  was **
  990          B    2758
  996          DSA  w18a
  997          B    2837
 1001          MN   kp1,work&X1
 1008          LCA  0&X3,w35
 1015          SAR  x1
 1019move13    C    x1,x2    move
 1026          BE   m13x       0&x1
 1031          LCA  0&X1,0&X3    up to
 1038          SAR  x1             0&x3
 1042          C    0&X3             until
 1046          SAR  x3                 x1 equal x2
 1050          B    move13
 1054m13x      C    0&X2
 1058          SAR  x1
 1062          BW   2928,flag
 1070          BCE  1101,w18b,*
 1078          BCE  1695,op,#
 1086          LCA  w18b,0&X3
 1093          SBR  x3
 1097          CW   1&X3
 1101          LCA  op,0&X3
 1108          SBR  x3
 1112          CW   1&X3
 1116          LCA  w35,0&X3
 1123          SBR  x3
 1127          SBR  x2
 1131          LCA  0&X1,0&X3
 1138          SAR  x1
 1142          C    0&X3
 1146          SAR  x3
 1150          BCE  1162,1&X1,}
 1158          B    1131
 1162          B    901
 1166          BCE  1178,op2,
 1174          B    1496
 1178          BCE  1663,op,#
 1186          BCE  1214,op,&
 1194          BCE  1214,op,*
 1202          BCE  1239,op,-
 1210          B    1527
 1214          LCA  w18a,w35    swap
 1221          LCA  w18b,w18a     w18a
 1228          LCA  w35,w18b        and w18b
 1235          B    974
 1239          BW   1379,flag
 1247          LCA  w18a,0&X2
 1254          LCA  kplus
 1258          SBR  x2
 1262          CW   2&X2,sawneg
 1269          LCA  w18b,w18a
 1276          LCA  kstar3,w18b
 1283          MCW  nop,op
 1290          CW   sawneg
 1294          SW   flag
 1298          B    974
     *
 1302          BCE  1328,w18b,*
 1310          MCW  op,1324
 1317          BCE  1391,3017,0
 1325          B
 1326          B
 1327          B
 1328          BW   *&5,flag
 1336          B    inner
 1340          B    1379
 1344          BW   1360,2&X2
 1352          SBR  x2
 1356          B    1344
 1360          SBR  x2,1&X2
 1367          BCE  1733,1&X2,}  gmark
 1375          B    inner
     *
 1379          SBR  1390
 1383          CW   1&X2
 1387          B    0
     *
 1391          BCE  1403,op2,
 1399          B    1440
 1403          MCW  op,op2
 1410          CW   1&X2
 1414          LCA  w18b,0&X2
 1421          SBR  x2
 1425          CW   keepwm
 1429          SBR  rwm1&3,1&X2  Remember where to clear WM
 1436          B    908
 1440          BCE  1476,op2,&
 1448          BCE  1476,op2,-
 1456          BCE  1410,op,*
 1464          BCE  1410,op,/
 1472          B    1328
 1476          BCE  1410,op,&
 1484          BCE  1410,op,-
 1492          B    1328
 1496          MCW  op,1510
 1503          BCE  1575,op2,0
 1511          BCE  1555,op2,&
 1519          BCE  1555,op2,-
 1527          BCE  1733,1&X2,}
 1535          BW   1328,flag
 1543          BW   inner,1&X2
 1551          B    1328
 1555          BCE  1575,op,&
 1563          BCE  1575,op,-
 1571          B    1527
 1575          BCE  1328,op,@
 1583          BW   1379,flag
 1591          C    0&X2,kb4
 1598          SAR  x3
 1602          MCW  0&X3,0&X2
 1609          SBR  x2
 1613          BCE  1644,op,-
 1621          MCW  op,0&X2
 1628          MCW  w18b
 1632          C    0&X2
 1636          SBR  x2
 1640          B    901
 1644          LCA  kplus,0&X2
 1651          SBR  x2
 1655          SW   flag
 1659          B    1269
 1663          B    2758
 1669          DSA  w18b
 1670          MCW  w18b,3021
 1677          MCW  3091,2972
 1684          A    kp1,2972
 1691          B    997
 1695          LCA  w35,0&X3
 1702          SBR  x2
 1706          LCA  op
 1710          SBR  x3
 1714          CW   1&X3
 1718          LCA  w18a,0&X3
 1725          LCA  gm
 1729          B    901
 1733          MCW  sx1,x1
 1740          SBR  3024,0&X2
 1747          BCE  1887,2&X2,,
 1755          BCE  1887,3019,<
 1763          BCE  1887,0&X2,$
 1771          BCE  1887,w18a,$
 1779          BM   1807,3062
 1787          BM   1887,3087
 1795          BWZ  1887,3087,S
 1803          B    1823
 1807          BWZ  1887,3087,2
 1815          BWZ  1887,3087,B
 1823          B    1887
 1827          LCA  w18a
 1831          LCA  w18b
 1835          LCA  lca
 1839          SBR  x3
 1843          CW   2&X3,5&X3
 1850          MZ   1852,3&X3
 1857          MZ   1859,6&X3
 1864          SBR  x1,6&X1
 1871          LCA  6&X2
 1875          LCA
 1876          SBR  x2,6&X2
 1883          B    loop
 1887          MCW  3027,3021
 1894          MCW  a001,x3
 1901          MCW  3027,3032
 1908          SBR  x1,4&X1
 1915          LCA  baritf&3
 1919          BCE  1963,work&X3,0
 1927          A    kp1,3032
 1934          MCW  3032,3021
 1941          MZ   3031,3021
 1948          A    kp1,x3
 1955          SW   flag
 1959          B    1919
 1963          LCA  assign,4&X1
 1970          LCA  3021
 1974          CW   4&X1
 1978          C    0&X1,baritf&3
 1985          BE   1994
 1990          CW   1&X1
 1994          LCA  gm,1&X2
 2001          C    0&X2
 2005          SAR  x2
 2009          BCE  2139,0&X2,#
 2017          BCE  2147,1&X2,$
 2025          MZ   2&X2,2&X1
 2032          SBR  x1,4&X1
 2039more      MCM  1&X2,1&X1
 2046          MN
 2047          SBR  x1
 2051          MCM  1&X2
 2055          MN
 2056          SAR  x2
 2060          BCE  more,0&X2,|
 2068          C    0&X2
 2072          SAR  x2
 2076          MCW  x3,sx3a
 2083          MCW  3041,0&X1
 2090          LCA  0&X2
 2094          SBR  x3
 2098          CW   0&X1,1&X3
 2105          C    0&X2
 2109          SAR  x3
 2113          BCE  2158,0&X3,}
 2121          SBR  x2,0&X3
 2128          MCW  sx3a,x3
 2135          B    1927
 2139          CW   1&X2
 2143          B    2001
 2147          MZ   3&X2,2&X1
 2154          B    2032
 2158          C    0&X1,kb4
 2165          SAR  x1
 2169          LCA  3041,0&X1
 2176          MCW  0&X2
 2180          MCW  3024,x2
 2187          BW   2217,6&X2
 2195          SW   3&X2
 2199          SBR  x1,9&X1
 2206          LCA  11&X2
 2210          SBR  x2,11&X2
 2217          SBR  x1,6&X1
 2224          LCA  6&X2
 2228          LCA
 2229          SBR  x2,6&X2
 2236          B    loop
 2240gm        dc   @}@
     work      equ  *&1
 2290          DCW  #50
 2340          dc   #50
 2390          dc   #50
 2440          dc   #50
 2490          dc   #50
 2540          dc   #50
 2572wrktop    dc   #32
     *
     * Skip subscript if present.  Copy the next operand into w18a
     * and  the next operator into op.  Bump X2 by 4.  If the
     * operand after the operator has a word mark, put stars into
     * w3b, else skip another subscript if present and put the
     * next operand into w3b and bump x3 by three.
     *
 2573setup     SBR  setupx&3
 2577          BCE  skpsub,1&X2,$
 2585          LCA  3&X2,w18a
 2592          MCW  4&X2,op
 2599          SBR  x2,4&X2
 2606          BW   *&5,keepwm
 2614rwm1      CW   0
 2618          SW   keepwm
 2622          BW   gotwm,1&X2
 2630          SW   1&X2
 2634          SBR  rwm2&3,1&X2  remember where to clear WM
 2641          MN   0&X2,*&15
 2648          MZ   0&X2,*&8
 2655          BCE  gotop,ops,0  &-*@.#
 2663          chain5
 2668          SW   flag
 2672gotwm     LCA  kstar3,w18b
 2679          B    setupx
 2683gotop     BCE  skpsub,1&X2,$
 2691          LCA  3&X2,w18b
 2698          SBR  x2,3&X2
 2705          BW   rwm2,1&X2
 2713          SW   1&X2,flag
 2720rwm2      CW   0
 2724setupx    B    0
     *
     * Skip subscript
     *
 2728skpsub    SBR  skpsux&3
 2732          SBR  x2,8&X2
 2739          BCE  skpsux,3&X2,$
 2747          SBR  x2,6&X2
 2754skpsux    B    0
     *
 2758          SBR  x1
 2762          SBR  2836,3&X1
 2769          MCW  2&X1,x1
 2776          MN   0&X1,3091
 2783          MN
 2784          MCW  3092
 2788          BWZ  2833,0&X1,2
 2796          A    kp100,3091
 2803          BWZ  2833,0&X1,S
 2811          A    kp100,3091
 2818          BM   2833,0&X1
 2826          A    kp100,3091
 2833          B    0
     *
 2837          SBR  2873
 2841          SBR  x3,0&X2
 2848          MCW  2972,x1
 2855          BW   2890,flag
 2863          C    x1,3091
 2870          BE   0
 2875          BCE  2917,work&X1,1
 2883          A    k3999,x1
 2890          BW   2906,2&X3
 2898          SBR  x3
 2902          B    2890
 2906          SBR  x3,1&X3
 2913          B    2863
 2917          A    k3999,x1
 2924          B    2863
 2928          CW   1&X3
 2932          B    1070
     *
 2936flag      dc   #1
 2937done      BSS  snapsh,C
 2942          SBR  clearl&3,gmwm
 2949          LCA  arith5,phasid
 2956          B    loadnx
     *
     * Data
     *
 2962sx3       DCW  #3
 2965sx1       DCW  #3
 2966op2       DCW  #1
 2969k3999     DSA  3999
 2972          DCW  #3
 2973kp1       dcw  &1
 3008w35       DCW  #35
 3009kplus     DCW  @&@
 3012kstar3    DCW  @***@
 3013nop       NOP
 3017          DCW  @&-*@@
 3018keepwm    DCW  #1
 3021          DCW  #3
 3024          DCW  #3
 3025lca       LCA
 3027          DCW  @01@
 3030a001      DSA  1
 3032          DCW  #2
 3033baritf    B    aritf  Entry to the arithmetic interpreter
 3037assign    dcw  @#@
 3040sx3a      DCW  #3
 3041          DCW  @|@
 3045kb4       DCW  #4
 3063w18a      DCW  #18
 3064op        DCW  #1
 3070ops       DCW  @&-*@.#@
 3088w18b      DCW  #18
 3091          DCW  #3
 3092          DCW  @0@
 3095kp100     dcw  &100
 3102arith5    DCW  @ARITH 5@
 3103gmwm      DCW  @}@
               org  201
  203          dsa  loaddd    load address for card-to-tape program
               ex   beginn
               END
